/*
	Installed from https://ui.angular-material.dev/
	Update this file using `npx @ngm-dev/cli update grid-lists/grid-list-10`
*/

export type Report = {
  name: string;
  description: string;
  lastEdited: string;
  authorInitials: string;
  href: string;
};

export const reports: Report[] = [
  {
    name: 'Retention – How many users return each week and month',
    description: 'Tracks user retention over weekly and monthly intervals.',
    lastEdited: '1 day ago',
    authorInitials: 'EK',
    href: '#',
  },
  {
    name: 'Revenue – By employee and role',
    description:
      'Analyzes revenue generated by employees based on their roles and contributions.',
    lastEdited: '2 days ago',
    authorInitials: 'SL',
    href: '#',
  },
  {
    name: 'Active users – Today',
    description:
      'Provides a snapshot of active users on the platform as of today.',
    lastEdited: '14 hours ago',
    authorInitials: 'AM',
    href: '#',
  },
  {
    name: 'Product Sales – Quarterly Report',
    description:
      'Details the sales performance of products over a quarterly timeframe.',
    lastEdited: '4 days ago',
    authorInitials: 'JR',
    href: '#',
  },
  {
    name: 'Customer Feedback – Survey Results',
    description:
      'Analyzes customer feedback survey results to gauge customer satisfaction.',
    lastEdited: '5 days ago',
    authorInitials: 'AC',
    href: '#',
  },
  {
    name: 'Marketing Campaign – Performance Analysis',
    description:
      'Examines the performance of marketing campaigns to return on investment (ROI).',
    lastEdited: '6 days ago',
    authorInitials: 'MS',
    href: '#',
  },
];
