/*
	Installed from https://ui.angular-material.dev/
	Update this file using `npx @ngm-dev/cli update grid-lists/grid-list-12`
*/

export type Editor = {
  name: string;
  imageUrl: string;
};

export type Report = {
  name: string;
  description: string;
  href: string;
  editors: Editor[];
};

export const reports: Report[] = [
  {
    name: 'Retention – How many users return each week and month',
    description: 'Tracks user retention over weekly and monthly intervals.',
    href: '#',
    editors: [
      {
        name: 'User A',
        imageUrl:
          'https://images.unsplash.com/photo-1527980965255-d3b416303d12?q=80&w=1887&auto=format&fit=facearea&&facepad=2&w=256&h=256',
      },
      {
        name: 'User B',
        imageUrl:
          'https://images.unsplash.com/photo-1619895862022-09114b41f16f?q=80&w=1887&auto=format&fit=facearea&&facepad=2&w=256&h=256',
      },
      {
        name: 'User C',
        imageUrl:
          'https://images.unsplash.com/photo-1569128782402-d1ec3d0c1b1b?q=80&w=1887&auto=format&fit=facearea&&facepad=2&w=256&h=256',
      },
    ],
  },
  {
    name: 'Revenue – By employee and role',
    description:
      'Analyzes revenue generated by employees based on their roles and contributions.',
    href: '#',
    editors: [
      {
        name: 'User A',
        imageUrl:
          'https://images.unsplash.com/photo-1527980965255-d3b416303d12?q=80&w=1887&auto=format&fit=facearea&&facepad=2&w=256&h=256',
      },
      {
        name: 'User B',
        imageUrl:
          'https://images.unsplash.com/photo-1566761284295-af58908238bb?q=80&w=1887&auto=format&fit=facearea&&facepad=2&w=256&h=256',
      },
      {
        name: 'User C',
        imageUrl:
          'https://images.unsplash.com/photo-1573496527892-904f897eb744?q=80&w=1887&auto=format&fit=facearea&&facepad=2&w=256&h=256',
      },
      {
        name: 'User D',
        imageUrl:
          'https://images.unsplash.com/photo-1569128782402-d1ec3d0c1b1b?q=80&w=1887&auto=format&fit=facearea&&facepad=2&w=256&h=256',
      },
    ],
  },
  {
    name: 'Active users – Today',
    description:
      'Provides a snapshot of active users on the platform as of today.',
    href: '#',
    editors: [
      {
        name: 'User A',
        imageUrl:
          'https://images.unsplash.com/photo-1527980965255-d3b416303d12?q=80&w=1887&auto=format&fit=facearea&&facepad=2&w=256&h=256',
      },
      {
        name: 'User B',
        imageUrl:
          'https://images.unsplash.com/photo-1573496527892-904f897eb744?q=80&w=1887&auto=format&fit=facearea&&facepad=2&w=256&h=256',
      },
    ],
  },
  {
    name: 'Product Sales – Quarterly Report',
    description:
      'Details the sales performance of products over a quarterly timeframe.',
    href: '#',
    editors: [
      {
        name: 'User A',
        imageUrl:
          'https://images.unsplash.com/photo-1621376225397-c1d357c68291?q=80&w=1887&auto=format&fit=facearea&&facepad=2&w=256&h=256',
      },
      {
        name: 'User B',
        imageUrl:
          'https://images.unsplash.com/photo-1585580568280-68b4f110cfdf?q=80&w=1887&auto=format&fit=facearea&&facepad=2&w=256&h=256',
      },
      {
        name: 'User C',
        imageUrl:
          'https://images.unsplash.com/photo-1573496527892-904f897eb744?q=80&w=1887&auto=format&fit=facearea&&facepad=2&w=256&h=256',
      },
    ],
  },
  {
    name: 'Customer Feedback – Survey Results',
    description:
      'Analyzes customer feedback survey results to gauge customer satisfaction.',
    href: '#',
    editors: [
      {
        name: 'User A',
        imageUrl:
          'https://images.unsplash.com/photo-1566761284295-af58908238bb?q=80&w=1887&auto=format&fit=facearea&&facepad=2&w=256&h=256',
      },
    ],
  },
  {
    name: 'Marketing Campaign – Performance Analysis',
    description:
      'Examines the performance of marketing campaigns to return on investment (ROI).',
    href: '#',
    editors: [
      {
        name: 'User A',
        imageUrl:
          'https://images.unsplash.com/photo-1527980965255-d3b416303d12?q=80&w=1887&auto=format&fit=facearea&&facepad=2&w=256&h=256',
      },
      {
        name: 'User B',
        imageUrl:
          'https://images.unsplash.com/photo-1619895862022-09114b41f16f?q=80&w=1887&auto=format&fit=facearea&&facepad=2&w=256&h=256',
      },
      {
        name: 'User C',
        imageUrl:
          'https://images.unsplash.com/photo-1569128782402-d1ec3d0c1b1b?q=80&w=1887&auto=format&fit=facearea&&facepad=2&w=256&h=256',
      },
    ],
  },
];
